export const PLANET_SANDBOX_WINDOW_WHITELIST = window['___PLANET_SANDBOX_WINDOW_WHITELIST___'];
export const PLANET_SANDBOX_DOCUMENT_WHITELIST = window['___PLANET_SANDBOX_DOCUMENT_WHITELIST___'];
export const SANDBOX_INSTANCE = Symbol.for('PLANET_SANDBOX_INSTANCE');
export const RAW_NODE = Symbol.for('PLANET_RAW_NODE');
export const WINDOW_BIND_FN = Symbol.for('PLANET_WINDOW_BIND_FN');
export const DOCUMENT_BIND_FN = Symbol.for('PLANET_DOCUMENT_BIND_FN');
